### ISSUE TITLE
Unable to convert this CSV file created from renderdoc

### ISSUE THREAD

**Issue by theboy181** [sergeyreznik/csv2obj#1]
[test.zip](https://github.com/sergeyreznik/csv2obj/files/4714210/test.zip)

I draged and dropped this file on the .exe and was unable to open the .obj file in 3d Paint on Windows 10.

**Comment by serhii-rieznik** [comment]
Hi!

This is purely console application, which also might be tweaked for very specific names in vertex layout.

It is pretty straightforward, and should be quite easy to build.
